services:
  db:
    platform: linux/arm64
    image: "arm64v8/mysql:8.0"
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: storage
    ports:
      - "3306:3306"
    volumes:
      - ./db/blueprint.sql:/docker-entrypoint-initdb.d/blueprint.sql
      - ./csvs:/var/lib/mysql-files # Mount CSV directory inside the MySQL container

  fastapi:
    build:
      context: ./fastAPI
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql+pymysql://root:root@db:3306/storage
    volumes:
      - ./fastAPI:/fastAPI
      - /fastAPI/__pycache__

  aiserver:
    platform: linux/arm64
    build:
      context: ./AIServer
      dockerfile: Dockerfile
    container_name: aiserver
    ports:
      - "5000:5000" # Expose the app on port 5000
    volumes:
      - ./AIServer:/code # Mount the local React directory to the container
    restart: always

  react:
    build:
      context: ./React
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./React:/app # Mount the local React directory to the container
      - /app/node_modules # Ignore node_modules to avoid overwriting during development
    environment:
      CHOKIDAR_USEPOLLING: "true"
