services:
  db:
    image: "arm64v8/mysql:latest" # Use ARM-compatible MySQL image
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: storage
    ports:
      - "3306:3306"
    volumes:
      - ./db/blueprint.sql:/docker-entrypoint-initdb.d/blueprint.sql
      - ./csvs:/var/lib/mysql-files

  adminer:
    container_name: adminer
    image: adminer:latest
    ports:
      - "4000:8080"
    restart: always
    depends_on:
      - db

  fastapi:
  build:
    context: ./fastAPI
    dockerfile: Dockerfile
  container_name: fastapi
  ports:
    - "8000:8000"
  restart: always
  depends_on:
    - db
  environment:
    DATABASE_URL: mysql+pymysql://root:root@db:3306/storage
  volumes:
    - ./fastAPI:/fastAPI
    - /fastAPI/__pycache__

  aiserver:
    build:
      context: ./AIServer
      dockerfile: Dockerfile
    container_name: aiserver
    ports:
      - "5000:5000"
    volumes:
      - ./AIServer:/code
    restart: always

  react:
    build:
      context: ./React
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./React:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
