services:

  fastapi:
    build:
      context: ./fastAPI
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    restart: always
    environment:
      DATABASE_URL: mysql+pymysql://root:PiYxia1331@192.168.0.102:3306/storage
  react:
    build:
      context: ./React
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
